spring:
  profiles:
    active: prod



#swagger
#swagger:
#  title: SWAGGER RESTFUL APIS
#  description: 扫描 【com.rrs.cdkinstall.bridge】 包
#  base-package: com.rrs.cdkinstall.bridge.controller
#  contact: siufung.chen
#  version: 1.0.1
